### ISSUE TITLE
import precice error

### ISSUE THREAD

**Issue by alicezanella** [precice/python-bindings#106]
Hi, 

I've just installed python-bindings and when I test the installation with `python3 -c "import precice"` this error appears: 

```
$ python3 -c "import precice"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zanella/softwares/pyprecice-2.2.0.2/precice/__init__.py", line 4, in <module>
    from cyprecice import Interface, action_read_iteration_checkpoint, action_write_iteration_checkpoint, action_write_initial_data, get_version_information
ImportError: /home/zanella/softwares/Python-3.9.0/lib/python3.9/site-packages/pyprecice-2.2.0.2-py3.9-linux-x86_64.egg/cyprecice.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK7precice15SolverInterface9getMeshIDERKSs
```

Does anyone know what could possibly cause it?

**Comment by BenjaminRodenberg** [comment]
Hi!

How did you install the package? Via `pip3 install pyprecice`, by checking out this repository and using the provided `setup.py` or in any other way?

**Comment by alicezanella** [comment]
I installed it via `setup.py` because on the server I'm working on I cannot use `apt-get` or `pip`, I can only install by source.
The command I used to install it is: 

`python3 setup.py build_ext --include-dirs=/home/zanella/softwares/precice/include --library-dirs=/home/zanella/softwares/precice/lib`

**Comment by IshaanDesai** [comment]
@alicezanella are you use that `pip` cannot be used on the server you are working on? If the issue is with admin rights then you can try:
```
pip3 install --user .
```
in the cloned `python-bindings` repository. Perhaps this helps.

Also something important to check: is preCICE built correctly? How did you build preCICE in this case?

**Comment by IshaanDesai** [comment]
Hi @alicezanella sorry for the very late response, it looks like the system you are running on really has problems with `pip`. Did you manage to resolve this or does the same problem still persist? 
If you have preCICE installed at custom paths, you can set environment variables as described [here](https://github.com/precice/python-bindings#precice-at-custom-location-setting-paths) before installing the python-bindings. Once the variables are set, you can try to run `python3 setup.py install --user` again.

**Comment by IshaanDesai** [comment]
Closing this issue due to inactivity, please reopen if another discussion is necessary.
