### ISSUE TITLE
Improve errors from `convert` function

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/python-bindings#175]
The error return by the [`convert` function](https://github.com/precice/python-bindings/blob/22a9d3adfd039e9b9c16e3e739cf67e743da8a0b/cyprecice/cyprecice.pyx#L15-L24) is not helpful at the moment. I stumbled over this when I organized my participant names in an `Enum`

```python
class ParticipantNames(Enum):
    MASS_LEFT = "Mass-Left"
    MASS_RIGHT = "Mass-Right"
```

One has to pass, for example, `ParticipantNames.MASS_LEFT.value` to the API. But I forgot the `.values` part, which led to an errors similar to

```python
>>> precice.Interface(1,2,3,4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cyprecice/cyprecice.pyx", line 87, in cyprecice.Interface.__cinit__
  File "cyprecice/cyprecice.pyx", line 24, in cyprecice.convert
TypeError: Could not convert.
```

I think it would be good to tell the user which type was received from the API and which types are supported here. If I would have known that I provided a `<enum 'ParticipantNames'>` instead of a `<class 'str'>` this would have helped me a lot debugging.

**Comment by BenjaminRodenberg** [comment]
Another point where this problem shows up: If you provide the path to the configuration file not as a string, but as a `pathlib.Path` (which I think is actually the preferrable way of doing things). I now have to convert a `pathlib.Path` to a `str` before handing it over to the python API.

**Comment by Shubham-Padkonde** [comment]
I reproduced this through the compiled bindings using the repository mock backend. Enum members, pathlib paths, integers and None all currently report only "Could not convert." for participant names, configuration filenames and mesh names. I am testing a focused diagnostic change that names the accepted str/bytes types and the received type, without changing conversion behavior or including argument values. Prepared with Codex assistance.
